### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by omnigenous** [hatredholder/bookbrowse#2]
https://aur.archlinux.org/

Please, consider publishing to Arch User Repositories!

**Comment by hatredholder** [comment]
> https://aur.archlinux.org/
> 
> Please, consider publishing to Arch User Repositories!

Thanks for opening the issue!

I've been thinking of adding this project onto some package repository, but wasn't sure if anyone would be interested.

Will work on this sometime closer to the weekend.

**Comment by omnigenous** [comment]
@hatredholder thanks!

Unfortunately I'm getting this error when trying to install

```
/home/user/.cache/yay/bookbrowse/PKGBUILD: line 16: cd: bookbrowse: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: bookbrowse-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
bookbrowse - exit status 4
```

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bookbrowse#n16

**Comment by hatredholder** [comment]
Looks like I messed up somewhere in the build steps. 😕

Just pushed an update, let me know if it works fine now.

**Comment by omnigenous** [comment]
Deleted ~/.cache/bookbrowse and after installing again it works. Thank you again!
